// SPDX-FileCopyrightText: 2026 Kavoye
// SPDX-License-Identifier: Apache-2.0
// Modified for WSurf by wsagency in 2026; based on Linen by Kavoye.

import Foundation

nonisolated enum AIDisclosure {
    static let replyCaption: LocalizedStringResource =
        "AI replies can be wrong. Check important info."

    static let onboardingCaption: LocalizedStringResource =
        "The assistant uses AI and is not a person. Responses can be wrong. Check important information."

    static let settingsCaption: LocalizedStringResource =
        "Replies are generated by AI and can contain mistakes. Check important info."

    @MainActor
    static func spokenPrefix() -> String {
        guard !hasSpokenDisclosure else { return "" }
        hasSpokenDisclosure = true
        return String(localized: "You’re talking to AI. ")
    }

    @MainActor
    static func resetSpokenDisclosure() {
        hasSpokenDisclosure = false
    }

    @MainActor
    private static var hasSpokenDisclosure = false
}
