// SPDX-FileCopyrightText: 2026 Kavoye
// SPDX-License-Identifier: Apache-2.0
// Modified for WSurf by wsagency in 2026; based on Linen by Kavoye.

import SwiftUI

struct AssistantVoiceConversationView: View {
    let coordinator: AppCoordinator
    var needsAnswer = false

    var body: some View {
        VStack(spacing: needsAnswer ? 8 : 16) {
            if !needsAnswer {
                Spacer(minLength: 12)
            }
            if let session = coordinator.conversationVoice {
                ConversationActivityIndicator(session: session, size: needsAnswer ? 56 : 184)
                Text(needsAnswer ? String(localized: "Review the request below") : session.statusText)
                    .font(.system(size: 17, weight: .medium))
                    .multilineTextAlignment(.center)
                if !needsAnswer && !session.usesEchoCancellation && session.isActive {
                    Text("Your microphone pauses while WSurf speaks.")
                        .font(.caption).foregroundStyle(.secondary).multilineTextAlignment(.center)
                }
                if let notice = session.inputNotice {
                    Text(notice).font(.callout).foregroundStyle(.secondary).multilineTextAlignment(.center)
                }
                if let failure = session.failure {
                    Text(failure).font(.callout).foregroundStyle(.secondary).multilineTextAlignment(.center)
                }
                if !needsAnswer && !session.transcript.isEmpty {
                    ConversationTranscript(session: session)
                } else if !needsAnswer {
                    Spacer(minLength: 12)
                }
            } else {
                Image(systemName: "waveform").font(.system(size: 48, weight: .light)).foregroundStyle(.secondary)
                Text(coordinator.voiceConversationMessage ?? String(localized: "Voice conversation"))
                    .font(.callout).multilineTextAlignment(.center)
                Spacer(minLength: 12)
            }

            HStack(spacing: 20) {
                if let session = coordinator.conversationVoice, session.isActive {
                    Button { session.toggleMicrophone() } label: {
                        Image(systemName: session.isMicrophoneMuted ? "mic.slash.fill" : "mic.fill")
                            .frame(width: 44, height: 44)
                            .background(Theme.Wash.hairline, in: Circle())
                    }
                    .disabled(session.isChangingMicrophone || session.phase == .connecting)
                    .accessibilityLabel(session.isMicrophoneMuted ? "Unmute microphone" : "Mute microphone")
                    .help(session.isMicrophoneMuted ? "Unmute microphone" : "Mute microphone")
                } else {
                    Button { coordinator.startVoiceConversation() } label: {
                        Image(systemName: "arrow.clockwise")
                            .frame(width: 44, height: 44)
                            .background(Theme.Wash.hairline, in: Circle())
                    }
                    .accessibilityLabel("Try Again")
                    .help("Try Again")
                }
                if let session = coordinator.conversationVoice, session.isActive {
                    Button { session.interruptReply() } label: {
                        Image(systemName: "stop.fill")
                            .font(.system(size: 14, weight: .semibold))
                            .frame(width: 44, height: 44)
                            .background(Theme.Wash.hairline, in: Circle())
                    }
                    .disabled(session.phase != .speaking)
                    .opacity(session.phase == .speaking ? 1 : 0.35)
                    .accessibilityLabel("Interrupt")
                    .help("Stop the reply and speak")
                }
                Button { coordinator.endVoiceConversation() } label: {
                    Image(systemName: "xmark")
                        .frame(width: 44, height: 44)
                        .background(Color.red.opacity(0.12), in: Circle())
                }
                .accessibilityLabel("End voice conversation")
                .help("End voice conversation and return to chat")
            }
            .font(.system(size: 17, weight: .medium))
            .buttonStyle(.plain)

            Text("OpenAI receives microphone audio during voice chat. The voice is generated by AI.")
                .font(.caption2).foregroundStyle(.secondary).multilineTextAlignment(.center)
        }
        .padding(.horizontal, 24)
        .padding(.bottom, 12)
        .frame(maxWidth: .infinity, maxHeight: needsAnswer ? nil : .infinity)
    }
}

private struct ConversationTranscript: View {
    let session: OpenAIRealtimeConversation

    var body: some View {
        ScrollViewReader { reader in
            ScrollView {
                LazyVStack(alignment: .leading, spacing: 16) {
                    ForEach(session.transcript) { line in
                        VStack(alignment: .leading, spacing: 4) {
                            Text(line.isUser ? "You" : "WSurf").font(.caption).foregroundStyle(.secondary)
                            Text(verbatim: line.text).font(.system(size: 15)).textSelection(.enabled)
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .id(line.id)
                    }
                }
            }
            .onChange(of: session.transcript.last?.text) {
                if let id = session.transcript.last?.id {
                    reader.scrollTo(id, anchor: .bottom)
                }
            }
        }
    }
}
