// SPDX-FileCopyrightText: 2026 Kavoye
// SPDX-License-Identifier: Apache-2.0
// Modified for WSurf by wsagency in 2026; based on Linen by Kavoye.

import AppKit
import SwiftUI

struct OpenAIOutputView: View {
    let output: OpenAIPresentation
    let providerID: String?
    let onOpenLink: (URL) -> Void
    @State private var failure: String?
    @State private var downloading = false

    var body: some View {
        VStack(alignment: .leading, spacing: 10) {
            ForEach(output.sources) { source in
                Button {
                    onOpenLink(source.url)
                } label: {
                    Label(source.title, systemImage: "link")
                        .lineLimit(2).multilineTextAlignment(.leading)
                }.buttonStyle(.link)
            }
            ForEach(output.pictures) { picture in
                OpenAIPictureView(picture: picture)
            }
            ForEach(output.files) { file in
                Button {
                    Task { await save(file) }
                } label: {
                    Label(file.name, systemImage: "arrow.down.doc")
                }.disabled(downloading)
            }
            if let failure {
                Text(failure).foregroundStyle(.secondary)
            }
        }
    }

    private func save(_ file: OpenAIPresentation.File) async {
        guard let provider = ProviderCatalog.shared.all.first(where: { $0.id == providerID }),
            let endpoint = provider.baseURL, provider.adapter == .openAIResponses
        else { return }
        downloading = true
        defer { downloading = false }
        do {
            let api = OpenAIAPI(transport: OpenAIHTTPTransport(baseURL: endpoint, apiKey: CredentialStore.key(for: provider) ?? ""))
            let result = try await api.download(file)
            try Task.checkCancellation()
            let panel = NSSavePanel()
            panel.nameFieldStringValue = URL(fileURLWithPath: file.name).lastPathComponent
            guard await panel.begin() == .OK, let url = panel.url else { return }
            try result.data.write(to: url, options: .atomic)
            failure = nil
        } catch { failure = String(localized: "The file could not be saved. It may have expired at OpenAI.") }
    }
}

private struct OpenAIPictureView: View {
    let picture: OpenAIPresentation.Picture
    @State private var image: NSImage?

    var body: some View {
        VStack(alignment: .leading, spacing: 6) {
            if let image {
                Image(nsImage: image).resizable().scaledToFit()
                    .accessibilityLabel("Image generated by OpenAI")
                Button("Save Image") {
                    Task {
                        let panel = NSSavePanel()
                        panel.nameFieldStringValue = "OpenAI image." + picture.format
                        guard await panel.begin() == .OK, let url = panel.url else { return }
                        do { try picture.data.write(to: url, options: .atomic) } catch { NSAlert(error: error).runModal() }
                    }
                }
            }
        }
        .task(id: picture.id) { image = NSImage(data: picture.data) }
    }
}
